### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by sanatbhadsavle** [mhammell-laboratory/TEsmall#13]
Hey Oliver,
I tried running TEsmall on a few files, I get this in my standard error file - 

```
2022-08-03 10:52:05,198 INFO Checking if reference genome and annotation files exist...
2022-08-03 10:52:05,199 INFO Downloading reference genome and annotation files...
--2022-08-03 10:52:05--  http://labshare.cshl.edu/shares/mhammelllab/www-data/TEsmall/mm10.tar.gz
Resolving labshare.cshl.edu (labshare.cshl.edu)... 143.48.220.222
Connecting to labshare.cshl.edu (labshare.cshl.edu)|143.48.220.222|:80... failed: Network is unreachable.
Traceback (most recent call last):
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/tarfile.py", line 2327, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/tarfile.py", line 1113, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/sw/eb/sw/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/tarfile.py", line 1049, in frombuf
    raise EmptyHeaderError("empty header")
tarfile.EmptyHeaderError: empty header
```

Is there something wrong at my end?

**Comment by olivertam** [comment]
Hi,

It could be that our [webserver](labshare.cshl.edu) was temporarily down. You can try again now (it is up as of this comment).
If you are still having trouble, it might be that the location where you are running TEsmall could not access the server. You could manually download it from [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEsmall/mm10.tar.gz) and decompress it (as `mm10` folder) into where the other genome files are stored (typically `$HOME/TEsmall_db/genomes/`).

Let me know if there are still issues.

Thanks
